#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Apr 30 08:30:54 CST 2026
maven-metadata-aliyunmaven.xml.lastUpdated=1777509054593
maven-metadata-central.xml.lastUpdated=1777509054596
maven-metadata-huaweicloud.xml.lastUpdated=1777509054592
maven-metadata-spring-milestones.xml.error=
maven-metadata-spring-milestones.xml.lastUpdated=1777509054594
maven-metadata-spring-snapshots.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1777509054595
