#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Apr 30 08:30:41 CST 2026
maven-metadata-aliyunmaven.xml.error=
maven-metadata-aliyunmaven.xml.lastUpdated=1777509041800
maven-metadata-huaweicloud.xml.error=
maven-metadata-huaweicloud.xml.lastUpdated=1777509041797
maven-metadata-spring-snapshots.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1777509041803
