package cn.weitee.erp.module.erp.service.finance;

import cn.hutool.core.util.ObjectUtil;
import cn.weitee.erp.module.erp.dal.dataobject.finance.ErpFinanceLedgerDO;
import cn.weitee.erp.module.erp.framework.event.VoucherGenerateFailedEvent;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

import jakarta.annotation.Resource;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.time.LocalDate;

@Service
@Validated
@Slf4j
public class ErpFinanceBizHookServiceImpl implements ErpFinanceBizHookService {

    @Resource
    private ErpFinanceLedgerService financeLedgerService;
    @Resource
    private ErpFinancePeriodService financePeriodService;
    @Resource
    private ErpFinanceVoucherService financeVoucherService;
    @Resource
    private ErpFinanceDualWriteService dualWriteService;
    @Resource
    private ApplicationEventPublisher eventPublisher;

    @Override
    public Long handleApprovedBiz(Integer bizType, Long bizId, LocalDate bizDate) {
        ErpFinanceLedgerDO defaultLedger = financeLedgerService.getDefaultFinanceLedger();
        if (defaultLedger != null) {
            financePeriodService.getCurrentOpenPeriod(defaultLedger.getId(),
                    ObjectUtil.defaultIfNull(bizDate, LocalDate.now()));
        }
        try {
            Long voucherId = financeVoucherService.autoGenerateVoucher(bizType, bizId);
            dualWriteService.syncDualWriteBySourceVoucherId(voucherId);
            return voucherId;
        } catch (Exception e) {
            // 凭证生成失败，发布告警事件，不阻断业务审核
            log.error("[handleApprovedBiz] 凭证生成失败，bizType={}, bizId={}", bizType, bizId, e);
            eventPublisher.publishEvent(new VoucherGenerateFailedEvent(
                    bizType, bizId,
                    e.getMessage(),
                    getStackTrace(e)
            ));
            // 不抛出异常，避免阻断业务审核流程
            return null;
        }
    }

    /**
     * 获取异常堆栈信息（限制长度）
     */
    private String getStackTrace(Exception e) {
        StringWriter sw = new StringWriter();
        e.printStackTrace(new PrintWriter(sw));
        String stackTrace = sw.toString();
        return stackTrace.length() > 500 ? stackTrace.substring(0, 500) : stackTrace;
    }

    @Override
    public void handleRollbackBiz(Integer bizType, Long bizId, Long userId, String remark) {
        financeVoucherService.rollbackAutoGeneratedVoucher(bizType, bizId, userId, remark);
    }

}
