package cn.weitee.erp.module.erp.enums.sale;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ErpSaleOrderClosureStageEnum {

    WAIT_SALE_APPROVAL("WAIT_SALE_APPROVAL"),
    WAIT_PURCHASE_SUGGEST_CONFIRM("WAIT_PURCHASE_SUGGEST_CONFIRM"),
    WAIT_PURCHASE_ORDER_CONVERT("WAIT_PURCHASE_ORDER_CONVERT"),
    WAIT_PURCHASE_APPROVAL("WAIT_PURCHASE_APPROVAL"),
    WAIT_PURCHASE_IQC("WAIT_PURCHASE_IQC"),
    WAIT_PURCHASE_STOCK_IN("WAIT_PURCHASE_STOCK_IN"),
    WAIT_PRODUCTION_SUGGEST_CONFIRM("WAIT_PRODUCTION_SUGGEST_CONFIRM"),
    WAIT_PRODUCTION_ORDER_CONVERT("WAIT_PRODUCTION_ORDER_CONVERT"),
    WAIT_DELIVERY_READY("WAIT_DELIVERY_READY"),
    PART_READY("PART_READY"),
    READY_TO_SHIP("READY_TO_SHIP"),
    CLOSED("CLOSED");

    private final String stage;
}
