package cn.iocoder.yudao.module.erp.service.finance;

import cn.hutool.core.util.ObjectUtil;
import cn.iocoder.yudao.module.erp.dal.dataobject.finance.ErpFinanceLedgerDO;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

import javax.annotation.Resource;
import java.time.LocalDate;

@Service
@Validated
public class ErpFinanceBizHookServiceImpl implements ErpFinanceBizHookService {

    @Resource
    private ErpFinanceLedgerService financeLedgerService;
    @Resource
    private ErpFinancePeriodService financePeriodService;
    @Resource
    private ErpFinanceVoucherService financeVoucherService;
    @Resource
    private ErpFinanceDualWriteService dualWriteService;

    @Override
    public Long handleApprovedBiz(Integer bizType, Long bizId, LocalDate bizDate) {
        ErpFinanceLedgerDO defaultLedger = financeLedgerService.getDefaultFinanceLedger();
        if (defaultLedger != null) {
            financePeriodService.getCurrentOpenPeriod(defaultLedger.getId(),
                    ObjectUtil.defaultIfNull(bizDate, LocalDate.now()));
        }
        Long voucherId = financeVoucherService.autoGenerateVoucher(bizType, bizId);
        dualWriteService.syncDualWriteBySourceVoucherId(voucherId);
        return voucherId;
    }

    @Override
    public void handleRollbackBiz(Integer bizType, Long bizId, Long userId, String remark) {
        financeVoucherService.rollbackAutoGeneratedVoucher(bizType, bizId, userId, remark);
    }

}
