package cn.iocoder.yudao.module.erp.service.finance;

import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.module.erp.controller.admin.finance.vo.voucher.ErpFinanceVoucherActionReqVO;
import cn.iocoder.yudao.module.erp.controller.admin.finance.vo.voucher.ErpFinanceVoucherGenerateReqVO;
import cn.iocoder.yudao.module.erp.controller.admin.finance.vo.voucher.ErpFinanceVoucherPageReqVO;
import cn.iocoder.yudao.module.erp.controller.admin.finance.vo.voucher.ErpFinanceVoucherReverseReqVO;
import cn.iocoder.yudao.module.erp.dal.dataobject.finance.ErpFinanceVoucherDO;
import cn.iocoder.yudao.module.erp.dal.dataobject.finance.ErpFinanceVoucherEntryDO;

import javax.validation.Valid;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.List;
import java.util.Map;

public interface ErpFinanceVoucherService {

    Long generateVoucher(@Valid ErpFinanceVoucherGenerateReqVO reqVO);

    Long autoGenerateVoucher(Integer bizType, Long bizId);

    void rollbackAutoGeneratedVoucher(Integer bizType, Long bizId, Long userId, String remark);

    Long recomputeAutoGeneratedVoucher(Integer bizType, Long bizId, Long userId, String remark);

    Long createMonthEndVoucher(Long ledgerId, String period, Map<String, BigDecimal> expenseSubjectAmounts,
                               String profitSubjectCode);

    void approveVoucher(Long userId, @Valid ErpFinanceVoucherActionReqVO reqVO);

    void cancelApproveVoucher(Long userId, @Valid ErpFinanceVoucherActionReqVO reqVO);

    void postVoucher(Long userId, @Valid ErpFinanceVoucherActionReqVO reqVO);

    void cancelPostVoucher(Long userId, @Valid ErpFinanceVoucherActionReqVO reqVO);

    Long reverseVoucher(Long userId, @Valid ErpFinanceVoucherReverseReqVO reqVO);

    ErpFinanceVoucherDO getVoucher(Long id);

    List<ErpFinanceVoucherDO> getVoucherListByIds(Collection<Long> ids);

    ErpFinanceVoucherDO getVoucherByLedgerAndBiz(Long ledgerId, Integer bizType, Long bizId);

    PageResult<ErpFinanceVoucherDO> getVoucherPage(ErpFinanceVoucherPageReqVO pageReqVO);

    List<ErpFinanceVoucherEntryDO> getVoucherEntryListByVoucherId(Long voucherId);

    List<ErpFinanceVoucherEntryDO> getVoucherEntryListByVoucherIds(Collection<Long> voucherIds);
}
