CREATE TABLE IF NOT EXISTS `erp_purchase_in_quality` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `no` varchar(64) NOT NULL COMMENT '质检单号',
  `purchase_in_id` bigint NOT NULL COMMENT '采购入库编号',
  `purchase_in_no` varchar(64) NOT NULL COMMENT '采购入库单号',
  `status` int NOT NULL COMMENT '质检单状态',
  `result` int NOT NULL COMMENT '质检结果',
  `checker_user_id` bigint DEFAULT NULL COMMENT '质检人',
  `check_time` datetime DEFAULT NULL COMMENT '质检时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '质检备注',
  `pass_count` decimal(24,6) NOT NULL DEFAULT '0.000000' COMMENT '合格总数',
  `reject_count` decimal(24,6) NOT NULL DEFAULT '0.000000' COMMENT '不合格总数',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_in_quality_no` (`no`),
  KEY `idx_purchase_in_quality_purchase_in_id` (`purchase_in_id`),
  KEY `idx_purchase_in_quality_status` (`status`),
  KEY `idx_purchase_in_quality_result` (`result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购入库轻量质检单';

CREATE TABLE IF NOT EXISTS `erp_purchase_in_quality_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `quality_id` bigint NOT NULL COMMENT '质检单编号',
  `purchase_in_item_id` bigint NOT NULL COMMENT '采购入库明细编号',
  `product_id` bigint NOT NULL COMMENT '产品编号',
  `warehouse_id` bigint NOT NULL COMMENT '仓库编号',
  `count` decimal(24,6) NOT NULL DEFAULT '0.000000' COMMENT '到货数量',
  `qa_pass_count` decimal(24,6) NOT NULL DEFAULT '0.000000' COMMENT '合格数量',
  `qa_reject_count` decimal(24,6) NOT NULL DEFAULT '0.000000' COMMENT '不合格数量',
  `qa_result` int NOT NULL DEFAULT '10' COMMENT '质检结果',
  `qa_remark` varchar(500) DEFAULT NULL COMMENT '质检备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_purchase_in_quality_item_quality_id` (`quality_id`),
  KEY `idx_purchase_in_quality_item_purchase_in_item_id` (`purchase_in_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 采购入库轻量质检单明细';
