spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:YOUR_OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:YOUR_ANTHROPIC_API_KEY}
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:YOUR_DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://127.0.0.1:11434}
      chat:
        model: llama3
    model:
      rerank: false
    mcp:
      server:
        enabled: true
        name: yudao-mcp-server
        version: 1.0.0
        instructions: 一个 MCP 示例服务
        sse-endpoint: /sse
      client:
        enabled: false
        name: mcp
        sse:
          connections:
            filesystem:
              url: ${MCP_REMOTE_URL:http://127.0.0.1:8089}
              sse-endpoint: /sse
        annotation-scanner:
          enabled: false
