-- 产品双账成本结果表
CREATE TABLE `erp_finance_dual_product_cost_result` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `product_id` BIGINT NOT NULL COMMENT '产品ID',
    `product_no` VARCHAR(64) DEFAULT NULL COMMENT '产品编号',
    `product_name` VARCHAR(255) DEFAULT NULL COMMENT '产品名称',
    `product_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '产品批次号',
    `production_order_id` BIGINT DEFAULT NULL COMMENT '生产工单ID',
    `production_order_no` VARCHAR(64) DEFAULT NULL COMMENT '生产工单编号',
    `period` VARCHAR(20) NOT NULL COMMENT '期间（YYYY-MM）',
    `external_material_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '材料成本-外部账',
    `internal_material_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '材料成本-内部账',
    `external_labor_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '人工成本-外部账',
    `internal_labor_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '人工成本-内部账',
    `external_overhead_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '制造费用-外部账',
    `internal_overhead_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '制造费用-内部账',
    `external_total_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '总成本-外部账',
    `internal_total_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '总成本-内部账',
    `diff_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '差异金额（内部-外部）',
    `status` TINYINT DEFAULT 0 COMMENT '状态（0-正常, 10-重建中）',
    `version_no` INT DEFAULT 1 COMMENT '版本号',
    `last_rebuild_time` DATETIME DEFAULT NULL COMMENT '最后重建时间',
    `last_rebuild_by` BIGINT DEFAULT NULL COMMENT '最后重建人',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_batch_order_period` (`product_id`, `product_batch_no`, `production_order_id`, `period`, `deleted`),
    KEY `idx_period` (`period`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_production_order` (`production_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品双账成本结果表';

-- 产品双账成本明细表
CREATE TABLE `erp_finance_dual_product_cost_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `result_id` BIGINT NOT NULL COMMENT '结果ID',
    `cost_component_type` TINYINT NOT NULL COMMENT '成本构成类型（10-材料, 20-人工, 30-制造费用）',
    `source_type` TINYINT NOT NULL COMMENT '来源类型（10-材料领用, 20-人工工时, 30-折旧, 40-电费, 50-其他）',
    `source_biz_type` INT DEFAULT NULL COMMENT '来源业务类型',
    `source_biz_id` BIGINT DEFAULT NULL COMMENT '来源业务ID',
    `source_no` VARCHAR(64) DEFAULT NULL COMMENT '来源单号',
    `product_id` BIGINT NOT NULL COMMENT '产品ID',
    `production_order_id` BIGINT DEFAULT NULL COMMENT '生产工单ID',
    `period` VARCHAR(20) NOT NULL COMMENT '期间',
    `external_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '外部账金额',
    `internal_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '内部账金额',
    `diff_amount` DECIMAL(18,2) DEFAULT 0.00 COMMENT '差异金额',
    `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (`id`),
    KEY `idx_result_id` (`result_id`),
    KEY `idx_product_period` (`product_id`, `period`),
    KEY `idx_source` (`source_biz_type`, `source_biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品双账成本明细表';

-- 产品双账成本重跑日志表
CREATE TABLE `erp_finance_dual_product_cost_rebuild_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `product_id` BIGINT NOT NULL COMMENT '产品ID',
    `product_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '产品批次号',
    `production_order_id` BIGINT DEFAULT NULL COMMENT '生产工单ID',
    `period` VARCHAR(20) NOT NULL COMMENT '期间',
    `status` TINYINT NOT NULL COMMENT '状态（10-成功, 20-失败, 30-进行中）',
    `trigger_type` TINYINT DEFAULT 10 COMMENT '触发类型（10-手动, 20-定时）',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
    `finished_at` DATETIME DEFAULT NULL COMMENT '结束时间',
    `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
    `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
    `affected_count` INT DEFAULT 0 COMMENT '影响记录数',
    `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (`id`),
    KEY `idx_product_period` (`product_id`, `period`),
    KEY `idx_production_order` (`production_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品双账成本重跑日志表';
