SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 0;
USE `ruoyi-vue-pro`;

INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (931308, '发货放行审核', 'erp:shipment-release:query', 2, 45, 930110, 'shipment-release', 'ep:release', 'erp/sale/shipment-release/index', 'ErpShipmentReleasePage', 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (931309, '市场执行台账', 'erp:market-ledger:query', 2, 46, 930110, 'market-ledger', 'ep:data-board', 'erp/sale/market-ledger/index', 'ErpMarketLedgerPage', 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (931310, '市场预警与统计', 'erp:market-alert:query', 2, 47, 930110, 'market-alert', 'ep:warning', 'erp/sale/market-alert/index', 'ErpMarketAlertPage', 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (931311, '合同导入', 'crm:contract:import', 2, 15, 930110, 'contract-import', 'ep:upload', 'crm/contract/import/index', 'CrmContractImportPage', 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (932020, '销项发票管理', 'erp:invoice:query', 2, 105, 930180, 'invoice', 'ep:receipt', 'erp/finance/invoice/index', 'ErpInvoicePage', 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (931408, '项目生命周期追踪', 'pmo:project:lifecycle:query', 2, 35, 930130, 'lifecycle', 'ep:guide', 'erp/project/lifecycle/index', 'ErpProjectLifecyclePage', 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);

INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93130801, '校验', 'erp:shipment-release:check', 3, 1, 931308, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93130802, '提交审核', 'erp:shipment-release:submit', 3, 2, 931308, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93130803, '审核通过', 'erp:shipment-release:approve', 3, 3, 931308, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93130804, '审核驳回', 'erp:shipment-release:reject', 3, 4, 931308, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93130901, '查询', 'erp:market-ledger:query', 3, 1, 931309, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93130902, '导出', 'erp:market-ledger:export', 3, 2, 931309, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93131001, '查询', 'erp:market-alert:query', 3, 1, 931310, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93131002, '更新规则', 'erp:market-alert:update', 3, 2, 931310, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93131003, '检查预警', 'erp:market-alert:check', 3, 3, 931310, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93202001, '查询', 'erp:invoice:query', 3, 1, 932020, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93202002, '新增', 'erp:invoice:create', 3, 2, 932020, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93202003, '修改', 'erp:invoice:update', 3, 3, 932020, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93202004, '删除', 'erp:invoice:delete', 3, 4, 932020, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93140801, '查询', 'pmo:project:lifecycle:query', 3, 1, 931408, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93140802, '更新阶段', 'pmo:project:lifecycle:update', 3, 2, 931408, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93131101, '下载模板', 'crm:contract:import:template', 3, 1, 931311, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (93131102, '导入', 'crm:contract:import:import', 3, 2, 931311, '', '', '', NULL, 0, 1, 1, 1, 'admin', NOW(), 'admin', NOW(), 0);

SET FOREIGN_KEY_CHECKS = 1;
