-- =====================================================
-- ERP AP estimate phase1
-- =====================================================

CREATE TABLE `erp_ap_estimate` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
    `estimate_no` VARCHAR(64) NOT NULL COMMENT 'estimate no',
    `estimate_month` VARCHAR(7) NOT NULL COMMENT 'estimate month',
    `source_biz_type` INT NOT NULL COMMENT 'source biz type',
    `source_biz_id` BIGINT NOT NULL COMMENT 'source biz id',
    `source_biz_no` VARCHAR(64) NOT NULL COMMENT 'source biz no',
    `source_purchase_in_id` BIGINT NOT NULL COMMENT 'source purchase in id',
    `source_purchase_in_no` VARCHAR(64) NOT NULL COMMENT 'source purchase in no',
    `source_order_id` BIGINT NULL COMMENT 'source order id',
    `source_order_no` VARCHAR(64) NULL COMMENT 'source order no',
    `supplier_id` BIGINT NOT NULL COMMENT 'supplier id',
    `account_id` BIGINT NULL COMMENT 'account id',
    `currency_code` VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT 'currency code',
    `source_amount` DECIMAL(24, 6) NOT NULL COMMENT 'source amount',
    `amount` DECIMAL(24, 6) NOT NULL COMMENT 'estimate amount',
    `status` INT NOT NULL DEFAULT 10 COMMENT 'estimate status',
    `confirm_user_id` BIGINT NULL COMMENT 'confirm user id',
    `confirm_time` DATETIME NULL COMMENT 'confirm time',
    `reverse_user_id` BIGINT NULL COMMENT 'reverse user id',
    `reverse_time` DATETIME NULL COMMENT 'reverse time',
    `reverse_remark` VARCHAR(255) NULL COMMENT 'reverse remark',
    `remark` VARCHAR(255) NULL COMMENT 'remark',
    `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'creator',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'updater',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT 'deleted',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT 'tenant id',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ap_estimate_no` (`tenant_id`, `estimate_no`, `deleted`),
    UNIQUE KEY `uk_ap_estimate_source` (`tenant_id`, `source_biz_type`, `source_biz_id`, `deleted`),
    KEY `idx_ap_estimate_month_status` (`tenant_id`, `estimate_month`, `status`, `deleted`),
    KEY `idx_ap_estimate_supplier` (`tenant_id`, `supplier_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP AP estimate';

CREATE TABLE `erp_ap_estimate_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
    `estimate_id` BIGINT NOT NULL COMMENT 'estimate id',
    `source_purchase_in_item_id` BIGINT NOT NULL COMMENT 'source purchase in item id',
    `source_purchase_in_id` BIGINT NOT NULL COMMENT 'source purchase in id',
    `source_purchase_in_no` VARCHAR(64) NOT NULL COMMENT 'source purchase in no',
    `source_order_id` BIGINT NULL COMMENT 'source order id',
    `source_order_item_id` BIGINT NULL COMMENT 'source order item id',
    `source_order_no` VARCHAR(64) NULL COMMENT 'source order no',
    `product_id` BIGINT NOT NULL COMMENT 'product id',
    `warehouse_id` BIGINT NULL COMMENT 'warehouse id',
    `project_id` BIGINT NULL COMMENT 'project id',
    `count` DECIMAL(24, 6) NOT NULL COMMENT 'count',
    `source_amount` DECIMAL(24, 6) NOT NULL COMMENT 'source amount',
    `tax_amount` DECIMAL(24, 6) NOT NULL COMMENT 'tax amount',
    `amount` DECIMAL(24, 6) NOT NULL COMMENT 'estimate amount',
    `remark` VARCHAR(255) NULL COMMENT 'remark',
    `creator` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'creator',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    `updater` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'updater',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT 'deleted',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT 'tenant id',
    PRIMARY KEY (`id`),
    KEY `idx_ap_estimate_item_estimate_id` (`tenant_id`, `estimate_id`, `deleted`),
    KEY `idx_ap_estimate_item_source_in_item` (`tenant_id`, `source_purchase_in_item_id`, `deleted`),
    KEY `idx_ap_estimate_item_project` (`tenant_id`, `project_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP AP estimate item';
