CREATE TABLE IF NOT EXISTS `erp_bom` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `bom_code` varchar(64) NOT NULL,
  `product_id` bigint NOT NULL,
  `version` varchar(32) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 1,
  `remark` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_bom_product_id` (`product_id`),
  KEY `idx_erp_bom_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_bom_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `bom_id` bigint NOT NULL,
  `material_id` bigint NOT NULL,
  `material_type` tinyint DEFAULT 0,
  `unit_id` bigint DEFAULT NULL,
  `usage_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `loss_rate` decimal(10,4) NOT NULL DEFAULT 0.0000,
  `lead_time_day` int DEFAULT 0,
  `sort` int DEFAULT 0,
  `remark` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_bom_item_bom_id` (`bom_id`),
  KEY `idx_erp_bom_item_material_id` (`material_id`),
  KEY `idx_erp_bom_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_material_plan_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `product_id` bigint NOT NULL,
  `supply_type` varchar(16) NOT NULL,
  `safety_stock` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `min_order_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `order_multiple` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `purchase_lead_day` int DEFAULT 0,
  `make_lead_day` int DEFAULT 0,
  `enable_flag` bit(1) NOT NULL DEFAULT b'1',
  `default_supplier_id` bigint DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_erp_material_plan_rule_product_id` (`tenant_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_mrp_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_no` varchar(64) NOT NULL,
  `plan_name` varchar(128) NOT NULL,
  `plan_start_date` date NOT NULL,
  `plan_end_date` date NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `run_time` datetime DEFAULT NULL,
  `operator_id` bigint DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_erp_mrp_plan_plan_no` (`tenant_id`, `plan_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_mrp_demand` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_id` bigint NOT NULL,
  `source_item_id` bigint DEFAULT NULL,
  `product_id` bigint NOT NULL,
  `demand_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `demand_date` date NOT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_mrp_demand_plan_id` (`plan_id`),
  KEY `idx_erp_mrp_demand_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_mrp_result` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `root_product_id` bigint NOT NULL,
  `material_id` bigint NOT NULL,
  `gross_demand_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `available_stock_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `incoming_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `wip_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `net_demand_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `suggest_type` varchar(16) DEFAULT NULL,
  `suggest_date` date DEFAULT NULL,
  `source_order_id` bigint DEFAULT NULL,
  `source_item_id` bigint DEFAULT NULL,
  `demand_date` date DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_mrp_result_plan_id` (`plan_id`),
  KEY `idx_erp_mrp_result_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_mrp_shortage` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `root_product_id` bigint NOT NULL,
  `material_id` bigint NOT NULL,
  `shortage_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `required_date` date NOT NULL,
  `source_order_id` bigint DEFAULT NULL,
  `source_item_id` bigint DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_mrp_shortage_plan_id` (`plan_id`),
  KEY `idx_erp_mrp_shortage_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_purchase_suggest` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `material_id` bigint NOT NULL,
  `suggest_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `suggest_arrival_date` date NOT NULL,
  `source_order_id` bigint DEFAULT NULL,
  `source_item_id` bigint DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `convert_purchase_order_id` bigint DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_suggest_plan_id` (`plan_id`),
  KEY `idx_erp_purchase_suggest_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_production_suggest` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `product_id` bigint NOT NULL,
  `suggest_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `suggest_start_date` date NOT NULL,
  `suggest_end_date` date NOT NULL,
  `source_order_id` bigint DEFAULT NULL,
  `source_item_id` bigint DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `convert_production_order_id` bigint DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_production_suggest_plan_id` (`plan_id`),
  KEY `idx_erp_production_suggest_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `erp_production_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_no` varchar(64) NOT NULL,
  `product_id` bigint NOT NULL,
  `plan_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `finished_qty` decimal(24,6) NOT NULL DEFAULT 0.000000,
  `plan_start_time` datetime NOT NULL,
  `plan_end_time` datetime NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `source_type` varchar(32) DEFAULT NULL,
  `source_id` bigint DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_erp_production_order_order_no` (`tenant_id`, `order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
